[package]
name = "liquid-resize-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.20.1"
egui_glow = "0.20.1"
glow = "0.11.2"
image = "0.24.5"
rfd = "0.10.0"
